{% set name = "PyALE" %}
{% set data = load_setup_py_data() %}
{% set version = data['version'] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    {% for package in data.get('setup_requires', {}) %}
      - {{ package.lower() }}
    {% endfor %}
  run:
    {% for req in data.get('install_requires', []) %}
      - {{ req }}
    {% endfor %}

test:
  imports:
    - PyALE
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DanaJomar/PyALE
  summary: ALE plots with python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - https://github.com/DanaJomar
