{% set name = "PyALE" %}
{% set data = load_setup_py_data() %}
{% set version = {{ data['version'] }} %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyALE-{{ version }}.tar.gz
  sha256: 9053617f54b53b4d5205585eab3ce86f210bd3d1e2c5aac4305edc0455b5dc0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    {% for package in data['setup_requires'] %}
      - {{ package.lower() }}
    {% endfor %}
  run:
    {% for req in data.get('install_requires', []) %}
      - {{ req }}
    {% endfor %}

test:
  imports:
    - PyALE
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DanaJomar/PyALE
  summary: ALE plots with python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - https://github.com/DanaJomar
