name: Test and Publish PyALE
on: push
jobs:
  test-coverage:
    name: Run tests and collect coverage report
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.10'
        - name: Generate Report
          run: |
            pip install -r requirements.txt
            coverage run -m --source=PyALE unittest discover -v
        - name: Upload Coverage to Codecov
          uses: codecov/codecov-action@v2
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
  publish-to-PyPi:
    name: Build and publish PyALE to TestPyPI
    runs-on: ubuntu-latest
    needs:
      - test-coverage
    permissions:
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write
    steps:
    - uses: actions/checkout@master
    - name: Setup Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install Wheel
      run: >-
        pip install wheel --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python setup.py sdist bdist_wheel
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
    - name: Publish to PyPI with new tag
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
  publish-to-conda:
    runs-on: ubuntu-latest
    needs:
      - test-coverage
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
        subDir: '.conda'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        override: true
        dry_run: true
